[package]
name = "bevy_sprite3d"
version = "4.0.0"
edition = "2021"

description = "Bevy Plugin to allow using 2d sprites in a 3d scene."
license = "MIT"
readme = "readme.md"
repository = "https://github.com/FraserLee/bevy_sprite3d"
keywords = ["gamedev", "bevy", "sprite", "3d"]

[dependencies.bevy]
path = "../bevy"
default-features = false
features = [
  "bevy_asset",
  "bevy_pbr",
  "bevy_sprite",
  "png"
]

[dev-dependencies]
rand = "0.8.5"

[dev-dependencies.bevy]
path = "../bevy"
default-features = false
features = [
  "bevy_state",
  "bevy_winit",
  "tonemapping_luts",
  "multi_threaded",
  "x11",
]
